services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    env_file:
      - ./.env
    # Adiciona o container à nossa rede customizada
    networks:
      - passagens_net
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    # Adiciona o container à nossa rede customizada
    networks:
      - passagens_net
    ports:
      - "5432:5432"

# Define a rede que os serviços usarão para se comunicar
networks:
  passagens_net:
    driver: bridge

volumes:
  postgres_data: